// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Participant struct {
	ID        int64
	Cuid      string
	Name      string
	Subpart   string
	CreatedAt time.Time
}
